name: "Build and Release APK"

on:
  push:
    branches:
      - master

jobs:
  export-android:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Godot Android Export
        uses: firebelley/godot-export@v5.2.1
        with:
          # Versión de Godot (Asegúrate de que coincida con la tuya)
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_export_templates.tpz
          relative_project_path: "./" # Donde está tu project.godot
          archive_output: true
          # IMPORTANTE: Este nombre debe ser el mismo que tienes en Godot > Exportar
          export_preset_name: "Android" 
        env:
          # Usamos tus secretos y el archivo JKS que subiste
          # Reemplaza 'nombre_de_tu_archivo.jks' por el real
          ANDROID_KEYSTORE_PATH: "tu_archivo.jks" 
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.1.${{ github.run_number }}
          name: "Build ${{ github.run_number }}"
          # La acción guarda el resultado en una carpeta específica
          files: /home/runner/.local/share/godot/builds/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
